services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - vemagendar_network

networks:
  vemagendar_network:
    external: true
